### ISSUE TITLE
digest section

### ISSUE THREAD

**Issue by lesliehoneybeefield** [chalkies/chalkies.github.io#1]
edit email to sfchalkboard-editor@lists.riseup.net. says editors.

**Comment by yardenac** [comment]
i wasn't quite sure what you mean here, but I just replaced it with a link to the other section. better IMO to be [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by lesliehoneybeefield** [comment]
good call. thanks!
